import re

def generate_case_variants(pattern):
    variants = []
    for match in re.finditer(r'[nN]', pattern):
        start, end = match.span()
        variants.append(pattern[:start] + pattern[start:end].lower() + pattern[end:])
        variants.append(pattern[:start] + pattern[start:end].upper() + pattern[end:])
    return variants

patterns = [
        {"1": r'Perú', "2": 'Territory', "3": 'Reyno'},
        {"1": r'América', "2": 'Territory', "3": 'Continente'},
        {"1": r'Indias', "2": 'Territory', "3": 'Continente'},
        {"1": r'Carolina', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Georgia', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Europa', "2": 'Territory', "3": 'Continente'},
        {"1": r'España', "2": 'Territory', "3": 'Reyno'},
        {"1": r'Italia', "2": 'Territory', "3": 'País'},
        {"1": r'Virginia', "2": 'Territory', "3": '@Provincia @Colonia'},
        {"1": r'Portugal', "2": 'Territory', "3": 'Reyno'},
        {"1": r'Alemania', "2": 'Territory', "3": 'País'},
        {"1": r'Francia', "2": 'Territory', "3": 'Reyno'},
        {"1": r'Chile', "2": 'Territory', "3": 'Reyno'},
        {"1": r'Inglaterra', "2": 'Territory', "3": 'Reyno'},
        {"1": r'Andalucía', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Vizcaya', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Castilla', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Galicia', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Cataluña', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Aragón', "2": 'Territory', "3": 'Reyno'},
        {"1": r'Brasil', "2": 'Territory', "3": 'Reyno'},
        {"1": r'Canadá', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Acadia', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Florida', "2": 'Territory', "3": 'Provincia'},
        {"1": r'San Juan de los Llanos', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Antioquia', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Chocó', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Florida', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Venezuela', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Nueva Andalucía', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Guayana', "2": 'Territory', "3": 'Reyno'},
        {"1": r'[nN]uevo [mM]undo', "2": 'Territory', "3": 'Reyno'},
        {"1": r'[nN]ueva España', "2": 'Territory', "3": 'Reyno'},
        {"1": r'[nN]uevo México', "2": 'Territory', "3": 'Reyno'},
        {"1": r'[nN]uevo Reyno de León', "2": 'Territory', "3": 'Reyno'},
        {"1": r'[nN]uevo Reyno de Granada', "2": 'Territory', "3": 'Reyno'},
        {"1": r'Tierra[ -]?[fF]irme', "2": 'Territory', "3": 'Reyno'},
        {"1": r'[nN]ueva Inglaterra', "2": 'Territory', "3": 'Provincia'},
        {"1": r'[nN]ueva Escocia', "2": 'Territory', "3": 'Provincia'},
        {"1": r'[nN]ueva Francia', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Bah[íi]a de Mass?achuss?ett?s', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Mass?achuss?ett?s', "2": 'Territory', "3": 'Provincia'},
        {"1": r'E[sx]tremadura', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Rio[xj]a', "2": 'Territory', "3": 'Provincia'},
        {"1": r'Antilles', "2": 'Landmark', "3": 'Islas'},
        {"1": r'Paraguay', "2": 'Landmark', "3": 'Río'},
        {"1": r'Apurimac', "2": 'Landmark', "3": 'Río'},
        {"1": r'Rimac', "2": 'Landmark', "3": 'Río'},
        {"1": r'Biobio', "2": 'Landmark', "3": 'Río'},
        {"1": r'Atrato', "2": 'Landmark', "3": 'Río'},
        {"1": r'Meta', "2": 'Landmark', "3": 'Río'},
        {"1": r'Apure', "2": 'Landmark', "3": 'Río'},
        {"1": r'Uruguay', "2": 'Landmark', "3": 'Río'},
        {"1": r'Orinoco', "2": 'Landmark', "3": 'Río'},
        {"1": r'Magdalena', "2": 'Landmark', "3": 'Río'},
        {"1": r'Portuguesa', "2": 'Landmark', "3": 'Río'},
        {"1": r'Putumayo', "2": 'Landmark', "3": 'Río'},
        {"1": r'Ohio', "2": 'Landmark', "3": 'Río'},
        {"1": r'Amazonas', "2": 'Landmark', "3": 'Río'},
        {"1": r'Madera', "2": 'Landmark', "3": 'Río'},
        {"1": r'Marañ[oó]n', "2": 'Landmark', "3": 'Río'},
        {"1": r'Pampas', "2": 'Landmark', "3": 'Llanuras'},
        {"1": r'Andes', "2": 'Landmark', "3": 'Cordillera'},
        {"1": r'Lima', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Buenos A[iy]res', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'M[eé]xico', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Santa F[eé]', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Santa F[eé] de Bogotá', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Trinidad de Buenos A[iy]res', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Santiago de Chile', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Guatemala', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Maule', "2": 'Landmark', "3": 'Río'},
        {"1": r'Tinguiririca', "2": 'Landmark', "3": 'Río'},
        {"1": r'Caracas', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Cuzco', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Charcas', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Sa?n?ta\. Cruz de la Sierra', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Cochabamba', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Montevideo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Colonia del Sacramento', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'C[oó]rdo[vb]a', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Salta', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Potos[íi]', "2": 'Settlement', "3": 'Villa'},
        {"1": r'Tarija', "2": 'Settlement', "3": 'Villa'},
        {"1": r'Huamanga', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Tru[xj]illo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Tarma', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Cuenca', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Corrientes', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Rio[jx|a', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Catamarca', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Santiago del Estero', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Arica', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Arequipa', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Caxamarca', "2": 'Settlement', "3": 'Villa'},
        {"1": r'Cuenca', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Quito', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Guayaquil', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Popay[áa]n', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'San Juan de Pasto', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Tunja', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Honda', "2": 'Settlement', "3": 'Villa'},
        {"1": r'Pamplona', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'M[oó]mpo[xs]', "2": 'Settlement', "3": 'Villa'},
        {"1": r'Carta[gx]ena', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'M[ée]rida', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Maracaibo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Sa?n?ta\.? Marta', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Barinas nueva', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Coro', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Barcelona', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Cuman[áa]', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Guayana', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Panam[aá]', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Porto[vb]elo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Veragua', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Sa?n?to\.? Domingo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Ha[bv]ana', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Cuba', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Guatemala', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Comayagua', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Le[oó]n', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Cartago', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'San Pablo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Todos Santos', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'r[íi]o Janeiro', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'[FP]ernambuco', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Nueva Yorck', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Bost[oó]n', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Filadelfia', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Baltimore', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Montr[ée]al', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Quebec', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Halifax', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Nuev[oa] Orleans', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Durango', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Monterr?e[iy]', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Sinaloa', "2": 'Settlement', "3": 'Villa'},
        {"1": r'Guadala[xj]ara', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Zacatecas', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Guana[jx]uato', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Michoac[áa]n', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Oaxaca', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Antequera', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Puebla', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Puebla de los Angeles', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Vera-?[cC]ruz', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Acapulco', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'México', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Quer[ée]taro', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Toluca', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'San Luis Potos[íi]', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Cholula', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Tla[xs]cala', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Monclova', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Saltillo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Cayena', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Madrid', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'París', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Londres', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Roma', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Venecia', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Sevilla', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Manila', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Barcelona', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Toledo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Alcántara', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Alcalá', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Avila', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Segovia', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Burgos', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Salamanca', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'C[aá]diz', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Valladolid', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Oviedo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Bilbao', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Coruña', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Valencia', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Zamora', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Granada', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'L[eé]rida', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Zaragoza', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'M[áa]laga', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Badajoz', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r'Medina del Campo', "2": 'Settlement', "3": 'Ciudad'},
        {"1": r"Misisipi", "2": "Landmark", "3": "Río"},
        {"1": r"Africa", "2": "Territory", "3": "Continente"},
        {"1": r"Ambato", "2": "Territory", "3": "Provincia"},
        {"1": r"America", "2": "Territory", "3": "Continente"},
        {"1": r"America Septentrional", "2": "Territory", "3": "Continente"},
        {"1": r"Araure", "2": "Territory", "3": "Jurisdicción"},
        {"1": r"Asangaro", "2": "Territory", "3": "Provincia"},
        {"1": r"Asia", "2": "Territory", "3": "Continente"},
        {"1": r"Asturias", "2": "Territory", "3": "Provincia"},
        {"1": r"Bahía de Marañan", "2": "Territory", "3": "Capitanía"},
        {"1": r"Barbada", "2": "Territory", "3": "Isla"},
        {"1": r"Barinas", "2": "Territory", "3": "Provincia"},
        {"1": r"Bridgetown", "2": "Territory", "3": "Partido"},
        {"1": r"Buenos-Ayres", "2": "Territory", "3": "Provincia"},
        {"1": r"Caicos", "2": "Territory", "3": "Islas"},
        {"1": r"California", "2": "Territory", "3": "Provincia"},
        {"1": r"Californias", "2": "Territory", "3": "Provincia"},
        {"1": r"Campeche", "2": "Territory", "3": "Provincia"},
        {"1": r"Canada", "2": "Territory", "3": "Provincia"},
        {"1": r"Castilla la Vieja", "2": "Territory", "3": "Reyno"},
        {"1": r"Caxamarquilla", "2": "Territory", "3": "Provincia"},
        {"1": r"Chachapoyas", "2": "Territory", "3": "Provincia"},
        {"1": r"Chaco", "2": "Territory", "3": "Provincia"},
        {"1": r"Chalco", "2": "Territory", "3": "Provincia"},
        {"1": r"Chancay", "2": "Territory", "3": "Provincia"},
        {"1": r"Chiapa", "2": "Territory", "3": "Provincia"},
        {"1": r"Chiloé", "2": "Territory", "3": "Provincia"},
        {"1": r"Chimbo", "2": "Territory", "3": "Provincia"},
        {"1": r"China", "2": "Territory", "3": "País"},
        {"1": r"Cinaloa", "2": "Territory", "3": "Provincia"},
        {"1": r"Concepción", "2": "Territory", "3": "Obispado"},
        {"1": r"Conchucos", "2": "Territory", "3": "Provincia"},
        {"1": r"Connecticut", "2": "Territory", "3": "Colonia"},
        {"1": r"Coquimbo", "2": "Territory", "3": "Provincia"},
        {"1": r"Darién", "2": "Territory", "3": "Provincia"},
        {"1": r"Dominica", "2": "Territory", "3": "Isla"},
        {"1": r"Dorado", "2": "Territory", "3": "Región"},
        {"1": r"Esmeraldas", "2": "Territory", "3": "Provincia"},
        {"1": r"estados unidos", "2": "Territory", "3": "País"},
        {"1": r"Estados Unidos de América", "2": "Territory", "3": "Provincia"},
        {"1": r"Estados unidos de la América", "2": "Territory", "3": "País"},
        {"1": r"Filipinas", "2": "Territory", "3": "Islas"},
        {"1": r"Flandes", "2": "Territory", "3": "Provincia"},
        {"1": r"Fuego", "2": "Territory", "3": "Isla"},
        {"1": r"gran Bretaña", "2": "Territory", "3": "País"},
        {"1": r"gran tierra", "2": "Territory", "3": "Partido"},
        {"1": r"Guadalabquen", "2": "Territory", "3": "Partido"},
        {"1": r"Guadalupe", "2": "Territory", "3": "Isla"},
        {"1": r"Guamanga", "2": "Territory", "3": "Provincia"},
        {"1": r"Guinea", "2": "Territory", "3": "Región"},
        {"1": r"Guipúzcoa", "2": "Territory", "3": "Provincia"},
        {"1": r"Holanda", "2": "Territory", "3": "País"},
        {"1": r"Honduras", "2": "Territory", "3": "Provincia"},
        {"1": r"Ibarra", "2": "Territory", "3": "Provincia"},
        {"1": r"Ilheos", "2": "Territory", "3": "Capitanía"},
        {"1": r"Imperio Mexicano", "2": "Territory", "3": "Imperio"},
        {"1": r"India", "2": "Territory", "3": "Región"},
        {"1": r"India Oriental", "2": "Territory", "3": "Región"},
        {"1": r"Isla de la Laxa", "2": "Territory", "3": "Provincia"},
        {"1": r"Jamayca", "2": "Territory", "3": "Isla"},
        {"1": r"Jersey Occidental", "2": "Territory", "3": "Provincia"},
        {"1": r"Jujui", "2": "Territory", "3": "Jurisdicción"},
        {"1": r"Labrador", "2": "Territory", "3": "Provincia"},
        {"1": r"Leiba", "2": "Territory", "3": "Provincia"},
        {"1": r"Loxa", "2": "Territory", "3": "Provincia"},
        {"1": r"Luisiana", "2": "Territory", "3": "Provincia"},
        {"1": r"Mainas", "2": "Territory", "3": "Provincia"},
        {"1": r"Mancha", "2": "Territory", "3": "Provincia"},
        {"1": r"Marañan", "2": "Territory", "3": "Capitanía"},
        {"1": r"Margarita", "2": "Territory", "3": "Isla"},
        {"1": r"Mariquita", "2": "Territory", "3": "Provincia"},
        {"1": r"Martinica", "2": "Territory", "3": "Isla"},
        {"1": r"Maryland", "2": "Territory", "3": "Colonia"},
        {"1": r"Mechoacán", "2": "Territory", "3": "Provincia"},
        {"1": r"Muzo", "2": "Territory", "3": "Provincia"},
        {"1": r"Navarra", "2": "Territory", "3": "Reyno"},
        {"1": r"Nicaragua", "2": "Territory", "3": "Provincia"},
        {"1": r"Nueva Galicia", "2": "Territory", "3": "Reyno"},
        {"1": r"Nueva Jersey", "2": "Territory", "3": "Colonia"},
        {"1": r"Nueva Vizcaya", "2": "Territory", "3": "Reyno"},
        {"1": r"nueva York", "2": "Territory", "3": "Colonia"},
        {"1": r"Nuevo Reyno", "2": "Territory", "3": "Reyno"},
        {"1": r"Oruro", "2": "Territory", "3": "Provincia"},
        {"1": r"Palma", "2": "Territory", "3": "Jurisdicción"},
        {"1": r"Pará", "2": "Territory", "3": "Capitanía"},
        {"1": r"Paria", "2": "Territory", "3": "Provincia"},
        {"1": r"Pasto", "2": "Territory", "3": "Provincia"},
        {"1": r"Pedraza", "2": "Territory", "3": "Jurisdicción"},
        {"1": r"Pensilvania", "2": "Territory", "3": "Colonia"},
        {"1": r"Piritu", "2": "Territory", "3": "Provincia"},
        {"1": r"Piritú", "2": "Territory", "3": "Provincia"},
        {"1": r"Piura", "2": "Territory", "3": "Provincia"},
        {"1": r"Puerto Rico", "2": "Territory", "3": "Isla"},
        {"1": r"Puerto Seguro", "2": "Territory", "3": "Capitanía"},
        {"1": r"Puertorico", "2": "Territory", "3": "Isla"},
        {"1": r"Puerto-rico", "2": "Territory", "3": "Isla"},
        {"1": r"Rey", "2": "Territory", "3": "Condado"},
        {"1": r"río Jeneyro", "2": "Territory", "3": "Capitanía"},
        {"1": r"Riobamba", "2": "Territory", "3": "Provincia"},
        {"1": r"Sagadahoc", "2": "Territory", "3": "Colonia"},
        {"1": r"San Christóval", "2": "Territory", "3": "Isla"},
        {"1": r"San Gil", "2": "Territory", "3": "Jurisdicción"},
        {"1": r"San Salvador", "2": "Territory", "3": "Provincia"},
        {"1": r"Santa Cruz de la Sierra", "2": "Territory", "3": "Provincia"},
        {"1": r"Santiago de las Atalayas", "2": "Territory", "3": "Jurisdicción"},
        {"1": r"Sinú", "2": "Territory", "3": "Partido"},
        {"1": r"Sonora", "2": "Territory", "3": "Provincia"},
        {"1": r"Surinam", "2": "Territory", "3": "Colonia"},
        {"1": r"Terranova", "2": "Territory", "3": "Isla"},
        {"1": r"Tocaima", "2": "Territory", "3": "Provincia"},
        {"1": r"Topia", "2": "Territory", "3": "Provincia"},
        {"1": r"Trinidad", "2": "Territory", "3": "Isla"},
        {"1": r"Valles", "2": "Territory", "3": "Provincia"},
        {"1": r"Vírgenes", "2": "Territory", "3": "Islas"},
        {"1": r'Paraná', "2": 'Landmark', "3": 'Río'}
    ]

# Convert each pattern into its own line with case variants
output = []
for idx, pattern in enumerate(patterns, start=1):
    case_variants = generate_case_variants(pattern["1"])
    for variant in case_variants:
        output.append({"1": r'%s' % variant, "2": pattern["2"], "3": pattern["3"], "index": idx})

# Print the result
for line in output:
    print(line)
